USE ac4ngos;
INSERT INTO AC_CODE2 (AC2_DESC, AC2_SC) VALUES ('LIABILITY','LI');
INSERT INTO AC_CODE2 (AC2_DESC, AC2_SC) VALUES ('EXPENSES','EX');
INSERT INTO AC_CODE2 (AC2_DESC, AC2_SC) VALUES ('ASSETS','AS');
INSERT INTO AC_CODE2 (AC2_DESC, AC2_SC) VALUES ('INCOME','IN');
#INSERT INTO AC_CODE3 (AC3_DESC) VALUES ('BANK');
#INSERT INTO AC_CODE3 (AC3_DESC) VALUES ('CASH');
#INSERT INTO AC_CODE3 (AC3_DESC) VALUES ('ADVANCE');

